### ISSUE TITLE
melpa: not found

### ISSUE THREAD

**Issue by andreas-roehler** [TobiasZawada/elgrep#4]
Just FYI, tried to install from melpa after M-x list-packages RET

Debugger entered--Lisp error: (file-error "https://melpa.org/packageselgrep-20190518.1539.el" "Not found")
  signal(file-error ("https://melpa.org/packageselgrep-20190518.1539.el" "Not found"))
  package--with-response-buffer-1("https://melpa.org/packages" #f(compiled-function () #<bytecode 0x397dcfb>) :file "elgrep-20190518.1539.el" :async nil :error-function #f(compiled-function () #<bytecode 0x27edee5>) :noerror nil)
  package-install-from-archive(#s(package-desc :name elgrep :version (20190518 1539) :summary "Searching files for regular expressions" :reqs ((emacs (25 1))) :kind single :archive "melpa" :dir nil :extras ((:commit . "c2c5858f335ac1d0013dc631e5bc2dc16d9b3198") (:keywords "tools" "matching" "files" "unix") (:authors ("Tobias Zawada" . "naehring@smtp.1und1.de")) (:maintainer "Tobias Zawada" . "naehring@smtp.1und1.de") (:url . "https://github.com/TobiasZawada/elgrep")) :signed nil))
  mapc(package-install-from-archive (#s(package-desc :name elgrep :version (20190518 1539) :summary "Searching files for regular expressions" :reqs ((emacs (25 1))) :kind single :archive "melpa" :dir nil :extras ((:commit . "c2c5858f335ac1d0013dc631e5bc2dc16d9b3198") (:keywords "tools" "matching" "files" "unix") (:authors ("Tobias Zawada" . "naehring@smtp.1und1.de")) (:maintainer "Tobias Zawada" . "naehring@smtp.1und1.de") (:url . "https://github.com/TobiasZawada/elgrep")) :signed nil)))
  package-download-transaction((#s(package-desc :name elgrep :version (20190518 1539) :summary "Searching files for regular expressions" :reqs ((emacs (25 1))) :kind single :archive "melpa" :dir nil :extras ((:commit . "c2c5858f335ac1d0013dc631e5bc2dc16d9b3198") (:keywords "tools" "matching" "files" "unix") (:authors ("Tobias Zawada" . "naehring@smtp.1und1.de")) (:maintainer "Tobias Zawada" . "naehring@smtp.1und1.de") (:url . "https://github.com/TobiasZawada/elgrep")) :signed nil)))
  package-install(#s(package-desc :name elgrep :version (20190518 1539) :summary "Searching files for regular expressions" :reqs ((emacs (25 1))) :kind single :archive "melpa" :dir nil :extras ((:commit . "c2c5858f335ac1d0013dc631e5bc2dc16d9b3198") (:keywords "tools" "matching" "files" "unix") (:authors ("Tobias Zawada" . "naehring@smtp.1und1.de")) (:maintainer "Tobias Zawada" . "naehring@smtp.1und1.de") (:url . "https://github.com/TobiasZawada/elgrep")) :signed nil) nil)
  package-install-button-action(#<marker (moves after insertion) at 56 in *Help*>)
  button-activate(#<marker (moves after insertion) at 56 in *Help*> nil)
  push-button(56)
  funcall-interactively(push-button 56)
  call-interactively(push-button nil nil)
  (prog1 (call-interactively cmd record-flag keys) (if (and (symbolp cmd) (get cmd 'byte-obsolete-info) (not (get cmd 'command-execute-obsolete-warned))) (progn (put cmd 'command-execute-obsolete-warned t) (message "%s" (macroexp--obsolete-warning cmd (get cmd 'byte-obsolete-info) "command")))))
  (cond ((arrayp final) (if record-flag (progn (add-to-history 'command-history (list 'execute-kbd-macro final prefixarg) nil t))) (execute-kbd-macro final prefixarg)) (t (prog1 (call-interactively cmd record-flag keys) (if (and (symbolp cmd) (get cmd 'byte-obsolete-info) (not (get cmd 'command-execute-obsolete-warned))) (progn (put cmd 'command-execute-obsolete-warned t) (message "%s" (macroexp--obsolete-warning cmd (get cmd ...) "command")))))))
  (let ((final cmd)) (while (progn (setq final (indirect-function final)) (if (autoloadp final) (setq final (autoload-do-load final cmd))))) (cond ((arrayp final) (if record-flag (progn (add-to-history 'command-history (list 'execute-kbd-macro final prefixarg) nil t))) (execute-kbd-macro final prefixarg)) (t (prog1 (call-interactively cmd record-flag keys) (if (and (symbolp cmd) (get cmd 'byte-obsolete-info) (not (get cmd ...))) (progn (put cmd 'command-execute-obsolete-warned t) (message "%s" (macroexp--obsolete-warning cmd ... "command"))))))))
  (if (and (symbolp cmd) (get cmd 'disabled) disabled-command-function) (run-hooks 'disabled-command-function) (let ((final cmd)) (while (progn (setq final (indirect-function final)) (if (autoloadp final) (setq final (autoload-do-load final cmd))))) (cond ((arrayp final) (if record-flag (progn (add-to-history 'command-history (list ... final prefixarg) nil t))) (execute-kbd-macro final prefixarg)) (t (prog1 (call-interactively cmd record-flag keys) (if (and (symbolp cmd) (get cmd ...) (not ...)) (progn (put cmd ... t) (message "%s" ...))))))))
  (let ((prefixarg (if special nil (prog1 prefix-arg (setq current-prefix-arg prefix-arg) (setq prefix-arg nil) (if current-prefix-arg (progn (prefix-command-update))))))) (if (and (symbolp cmd) (get cmd 'disabled) disabled-command-function) (run-hooks 'disabled-command-function) (let ((final cmd)) (while (progn (setq final (indirect-function final)) (if (autoloadp final) (setq final (autoload-do-load final cmd))))) (cond ((arrayp final) (if record-flag (progn (add-to-history ... ... nil t))) (execute-kbd-macro final prefixarg)) (t (prog1 (call-interactively cmd record-flag keys) (if (and ... ... ...) (progn ... ...))))))))
  command-execute(push-button)

**Comment by TobiasZawada** [comment]
Thanks for your info.
I don't think I can tackle that problem allone.
I opened a Melpa-issue for it: https://github.com/melpa/melpa/issues/6254

BTW. I added dependency info for the package and a corresponding `require`.
But I do not think that those modifications fix the problem.

**Comment by conao3** [comment]
Yes. https://melpa.org/packageselgrep-20190518.1539.el doesn't has a file but https://melpa.org/packages/elgrep-20190701.1207.el has a file (now (because version number will change every upstream commit)).
You may be set `pakcage-archives` without slash tail of url, doesn't it?

**Comment by TobiasZawada** [comment]
@conao3 Thanks for the message. Looks like elgrep can be installed via melpa again.
The bad thing is that I do not know why this happened and I do not know what I should do to avoid that problem in the future.

**Comment by andreas-roehler** [comment]
Error still happens here. When trying to install just some other packages, got a similar error. 

Also received that: Debugger entered--Lisp error: (error "Error retrieving: https://melpa.org/packagesarchive-contents (error http 404)")
  signal(error ("Error retrieving: https://melpa.org/packagesarchive-contents (error http 404)"))
  #f(compiled-function (status) #<bytecode 0x38a20d7>)((:error (error http 404) :peer (:certificate [...]

Seems something got wrong with a certificate.

**Comment by andreas-roehler** [comment]
Hi Tobias, it turns out an edit of my emacs-init file went wrong weeks ago without noticing it. Also couldn't relate that error message earlier. Sorry for the noise.
